pipeline {
    agent any 
    environment {
        IMAGE_NAME = 'flask-app'
        DOCKERHUB_USER = 'ikhlasrtb'
    }
    stages {
        stage('Build Image') {
            steps {
                sh "docker build -t ${DOCKERHUB_USER}/${IMAGE_NAME}:latest ."
            }
        }
        stage('Dockerhub Login') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                    sh "echo \$PASSWORD | docker login -u \$USERNAME --password-stdin"
                }
            }
        }
        stage('Push to Dockerhub'){
            steps {
                sh "docker push ${DOCKERHUB_USER}/${IMAGE_NAME}:latest"
            }
        }
    }
}